from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from util import validate_register_form, create_tables

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 395)
        MainWindow.setMinimumSize(QtCore.QSize(590, 395))
        MainWindow.setMaximumSize(QtCore.QSize(850, 569))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.cityChoice = QtWidgets.QComboBox(self.widget)
        self.cityChoice.setGeometry(QtCore.QRect(110, 238, 140, 20))
        self.cityChoice.setObjectName("cityChoice")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.cityChoice.addItem("")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(20, 155, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 70, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 65, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.registerEmail = QtWidgets.QPlainTextEdit(self.widget)
        self.registerEmail.setGeometry(QtCore.QRect(110, 15, 140, 24))
        self.registerEmail.setObjectName("registerEmail")
        self.registerPw = QtWidgets.QPlainTextEdit(self.widget)
        self.registerPw.setGeometry(QtCore.QRect(110, 60, 140, 24))
        self.registerPw.setObjectName("registerPw")
        self.registerPwConfirm = QtWidgets.QPlainTextEdit(self.widget)
        self.registerPwConfirm.setGeometry(QtCore.QRect(110, 105, 140, 24))
        self.registerPwConfirm.setObjectName("registerPwConfirm")
        self.registerName = QtWidgets.QPlainTextEdit(self.widget)
        self.registerName.setGeometry(QtCore.QRect(110, 150, 140, 24))
        self.registerName.setObjectName("registerName")
        self.registerSurname = QtWidgets.QPlainTextEdit(self.widget)
        self.registerSurname.setGeometry(QtCore.QRect(110, 195, 140, 24))
        self.registerSurname.setObjectName("registerSurname")
        self.registerButton = QtWidgets.QPushButton(self.widget)
        self.registerButton.setGeometry(QtCore.QRect(80, 290, 111, 41))
        self.registerButton.setObjectName("registerButton")
        self.horizontalLayout.addWidget(self.widget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(110, 20, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.loginEmail = QtWidgets.QPlainTextEdit(self.widget_2)
        self.loginEmail.setGeometry(QtCore.QRect(35, 60, 200, 24))
        self.loginEmail.setObjectName("loginEmail")
        self.loginPw = QtWidgets.QPlainTextEdit(self.widget_2)
        self.loginPw.setGeometry(QtCore.QRect(35, 160, 200, 24))
        self.loginPw.setPlainText("")
        self.loginPw.setObjectName("loginPw")
        self.loginButton = QtWidgets.QPushButton(self.widget_2)
        self.loginButton.setGeometry(QtCore.QRect(80, 290, 111, 41))
        self.loginButton.setObjectName("loginButton")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(116, 120, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.rememberMeCBox = QtWidgets.QCheckBox(self.widget_2)
        self.rememberMeCBox.setGeometry(QtCore.QRect(170, 230, 81, 17))
        self.rememberMeCBox.setObjectName("rememberMeCBox")
        self.keepSignedInCBox = QtWidgets.QCheckBox(self.widget_2)
        self.keepSignedInCBox.setGeometry(QtCore.QRect(30, 230, 121, 17))
        self.keepSignedInCBox.setObjectName("keepSignedInCBox")
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.registerButton.clicked.connect(self.register)
        self.loginButton.clicked.connect(self.login)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YemekSepeti"))
        self.cityChoice.setItemText(0, _translate("MainWindow", "Adana"))
        self.cityChoice.setItemText(1, _translate("MainWindow", "Adıyaman"))
        self.cityChoice.setItemText(2, _translate("MainWindow", "Afyon"))
        self.cityChoice.setItemText(3, _translate("MainWindow", "Ağrı"))
        self.cityChoice.setItemText(4, _translate("MainWindow", "Amasya"))
        self.cityChoice.setItemText(5, _translate("MainWindow", "Ankara"))
        self.cityChoice.setItemText(6, _translate("MainWindow", "Antalya"))
        self.cityChoice.setItemText(7, _translate("MainWindow", "Artvin"))
        self.cityChoice.setItemText(8, _translate("MainWindow", "Aydın"))
        self.cityChoice.setItemText(9, _translate("MainWindow", "Balıkesir"))
        self.cityChoice.setItemText(10, _translate("MainWindow", "Bilecik"))
        self.cityChoice.setItemText(11, _translate("MainWindow", "Bingöl"))
        self.cityChoice.setItemText(12, _translate("MainWindow", "Bitlis"))
        self.cityChoice.setItemText(13, _translate("MainWindow", "Bolu"))
        self.cityChoice.setItemText(14, _translate("MainWindow", "Burdur"))
        self.cityChoice.setItemText(15, _translate("MainWindow", "Bursa"))
        self.cityChoice.setItemText(16, _translate("MainWindow", "Çanakkale"))
        self.cityChoice.setItemText(17, _translate("MainWindow", "Çankırı"))
        self.cityChoice.setItemText(18, _translate("MainWindow", "Çorum"))
        self.cityChoice.setItemText(19, _translate("MainWindow", "Denizli"))
        self.cityChoice.setItemText(20, _translate("MainWindow", "Diyarbakır"))
        self.cityChoice.setItemText(21, _translate("MainWindow", "Edirne"))
        self.cityChoice.setItemText(22, _translate("MainWindow", "Elazığ"))
        self.cityChoice.setItemText(23, _translate("MainWindow", "Erzincan"))
        self.cityChoice.setItemText(24, _translate("MainWindow", "Erzurum"))
        self.cityChoice.setItemText(25, _translate("MainWindow", "Eskişehir"))
        self.cityChoice.setItemText(26, _translate("MainWindow", "Gaziantep"))
        self.cityChoice.setItemText(27, _translate("MainWindow", "Giresun"))
        self.cityChoice.setItemText(28, _translate("MainWindow", "Gümüşhane"))
        self.cityChoice.setItemText(29, _translate("MainWindow", "Hakkari"))
        self.cityChoice.setItemText(30, _translate("MainWindow", "Hatay"))
        self.cityChoice.setItemText(31, _translate("MainWindow", "Isparta"))
        self.cityChoice.setItemText(32, _translate("MainWindow", "Mersin"))
        self.cityChoice.setItemText(33, _translate("MainWindow", "İstanbul"))
        self.cityChoice.setItemText(34, _translate("MainWindow", "İzmir"))
        self.cityChoice.setItemText(35, _translate("MainWindow", "Kars"))
        self.cityChoice.setItemText(36, _translate("MainWindow", "Kastamonu"))
        self.cityChoice.setItemText(37, _translate("MainWindow", "Kayseri"))
        self.cityChoice.setItemText(38, _translate("MainWindow", "Kırklareli"))
        self.cityChoice.setItemText(39, _translate("MainWindow", "Kırşehir"))
        self.cityChoice.setItemText(40, _translate("MainWindow", "Kocaeli"))
        self.cityChoice.setItemText(41, _translate("MainWindow", "Konya"))
        self.cityChoice.setItemText(42, _translate("MainWindow", "Kütahya"))
        self.cityChoice.setItemText(43, _translate("MainWindow", "Malatya"))
        self.cityChoice.setItemText(44, _translate("MainWindow", "Manisa"))
        self.cityChoice.setItemText(45, _translate("MainWindow", "Kahramanmaraş"))
        self.cityChoice.setItemText(46, _translate("MainWindow", "Mardin"))
        self.cityChoice.setItemText(47, _translate("MainWindow", "Muğla"))
        self.cityChoice.setItemText(48, _translate("MainWindow", "Muş"))
        self.cityChoice.setItemText(49, _translate("MainWindow", "Nevşehir"))
        self.cityChoice.setItemText(50, _translate("MainWindow", "Niğde"))
        self.cityChoice.setItemText(51, _translate("MainWindow", "Ordu"))
        self.cityChoice.setItemText(52, _translate("MainWindow", "Rize"))
        self.cityChoice.setItemText(53, _translate("MainWindow", "Sakarya"))
        self.cityChoice.setItemText(54, _translate("MainWindow", "Samsun"))
        self.cityChoice.setItemText(55, _translate("MainWindow", "Siirt"))
        self.cityChoice.setItemText(56, _translate("MainWindow", "Sinop"))
        self.cityChoice.setItemText(57, _translate("MainWindow", "Sivas"))
        self.cityChoice.setItemText(58, _translate("MainWindow", "Tekirdağ"))
        self.cityChoice.setItemText(59, _translate("MainWindow", "Tokat"))
        self.cityChoice.setItemText(60, _translate("MainWindow", "Trabzon"))
        self.cityChoice.setItemText(61, _translate("MainWindow", "Tunceli"))
        self.cityChoice.setItemText(62, _translate("MainWindow", "Şanlıurfa"))
        self.cityChoice.setItemText(63, _translate("MainWindow", "Uşak"))
        self.cityChoice.setItemText(64, _translate("MainWindow", "Van"))
        self.cityChoice.setItemText(65, _translate("MainWindow", "Yozgat"))
        self.cityChoice.setItemText(66, _translate("MainWindow", "Zonguldak"))
        self.cityChoice.setItemText(67, _translate("MainWindow", "Aksaray"))
        self.cityChoice.setItemText(68, _translate("MainWindow", "Bayburt"))
        self.cityChoice.setItemText(69, _translate("MainWindow", "Karaman"))
        self.cityChoice.setItemText(70, _translate("MainWindow", "Kırıkkale"))
        self.cityChoice.setItemText(71, _translate("MainWindow", "Batman"))
        self.cityChoice.setItemText(72, _translate("MainWindow", "Şırnak"))
        self.cityChoice.setItemText(73, _translate("MainWindow", "Bartın"))
        self.cityChoice.setItemText(74, _translate("MainWindow", "Ardahan"))
        self.cityChoice.setItemText(75, _translate("MainWindow", "Iğdır"))
        self.cityChoice.setItemText(76, _translate("MainWindow", "Yalova"))
        self.cityChoice.setItemText(77, _translate("MainWindow", "Karabük"))
        self.cityChoice.setItemText(78, _translate("MainWindow", "Kilis"))
        self.cityChoice.setItemText(79, _translate("MainWindow", "Osmaniye"))
        self.cityChoice.setItemText(80, _translate("MainWindow", "Düzce"))
        self.label_5.setText(_translate("MainWindow", "Ad"))
        self.label_3.setText(_translate("MainWindow", "Soyad"))
        self.label_4.setText(_translate("MainWindow", "E-Posta"))
        self.label_2.setText(_translate("MainWindow", "Şifre Tekrar"))
        self.label.setText(_translate("MainWindow", "Şifre"))
        self.label_6.setText(_translate("MainWindow", "Şehir"))
        self.registerButton.setText(_translate("MainWindow", "Kayıt Ol"))
        self.label_7.setText(_translate("MainWindow", "E-Posta"))
        self.loginButton.setText(_translate("MainWindow", "Giriş Yap"))
        self.label_8.setText(_translate("MainWindow", "Şifre"))
        self.rememberMeCBox.setText(_translate("MainWindow", "Beni Hatırla"))
        self.keepSignedInCBox.setText(_translate("MainWindow", "Oturumumu açık tut"))

    def register(self):
        register_form = {
            "email" : self.registerEmail.toPlainText(),
            "name" : self.registerName.toPlainText(),
            "surname" : self.registerSurname.toPlainText(),
            "password" : self.registerPw.toPlainText(),
            "password_confirmation" : self.registerPwConfirm.toPlainText(),
        }
        # validation = validate_register_form(register_form)

    def login(self):
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

