from PyQt5 import QtCore, QtGui, QtWidgets
import util
from sqlite3 import OperationalError, IntegrityError

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 395)
        MainWindow.setMinimumSize(QtCore.QSize(590, 395))
        MainWindow.setMaximumSize(QtCore.QSize(850, 569))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.cityChoice = QtWidgets.QComboBox(self.widget)
        self.cityChoice.setGeometry(QtCore.QRect(110, 238, 140, 20))
        self.cityChoice.setObjectName("cityChoice")
        self.cityChoice.addItem("Adana")
        self.cityChoice.addItem("Adıyaman")
        self.cityChoice.addItem("Afyon")
        self.cityChoice.addItem("Ağrı")
        self.cityChoice.addItem("Amasya")
        self.cityChoice.addItem("Ankara")
        self.cityChoice.addItem("Antalya")
        self.cityChoice.addItem("Artvin")
        self.cityChoice.addItem("Aydın")
        self.cityChoice.addItem("Balıkesir")
        self.cityChoice.addItem("Bilecik")
        self.cityChoice.addItem("Bingöl")
        self.cityChoice.addItem("Bitlis")
        self.cityChoice.addItem("Bolu")
        self.cityChoice.addItem("Burdur")
        self.cityChoice.addItem("Bursa")
        self.cityChoice.addItem("Çanakkale")
        self.cityChoice.addItem("Çankırı")
        self.cityChoice.addItem("Çorum")
        self.cityChoice.addItem("Denizli")
        self.cityChoice.addItem("Diyarbakır")
        self.cityChoice.addItem("Edirne")
        self.cityChoice.addItem("Elazığ")
        self.cityChoice.addItem("Erzincan")
        self.cityChoice.addItem("Erzurum")
        self.cityChoice.addItem("Eskişehir")
        self.cityChoice.addItem("Gaziantep")
        self.cityChoice.addItem("Giresun")
        self.cityChoice.addItem("Gümüşhane")
        self.cityChoice.addItem("Hakkari")
        self.cityChoice.addItem("Hatay")
        self.cityChoice.addItem("Isparta")
        self.cityChoice.addItem("Mersin")
        self.cityChoice.addItem("İstanbul")
        self.cityChoice.addItem("İzmir")
        self.cityChoice.addItem("Kars")
        self.cityChoice.addItem("Kastamonu")
        self.cityChoice.addItem("Kayseri")
        self.cityChoice.addItem("Kırklareli")
        self.cityChoice.addItem("Kırşehir")
        self.cityChoice.addItem("Kocaeli")
        self.cityChoice.addItem("Konya")
        self.cityChoice.addItem("Kütahya")
        self.cityChoice.addItem("Malatya")
        self.cityChoice.addItem("Manisa")
        self.cityChoice.addItem("Kahramanmaraş")
        self.cityChoice.addItem("Mardin")
        self.cityChoice.addItem("Muğla")
        self.cityChoice.addItem("Muş")
        self.cityChoice.addItem("Nevşehir")
        self.cityChoice.addItem("Niğde")
        self.cityChoice.addItem("Ordu")
        self.cityChoice.addItem("Rize")
        self.cityChoice.addItem("Sakarya")
        self.cityChoice.addItem("Samsun")
        self.cityChoice.addItem("Siirt")
        self.cityChoice.addItem("Sinop")
        self.cityChoice.addItem("Sivas")
        self.cityChoice.addItem("Tekirdağ")
        self.cityChoice.addItem("Tokat")
        self.cityChoice.addItem("Trabzon")
        self.cityChoice.addItem("Tunceli")
        self.cityChoice.addItem("Şanlıurfa")
        self.cityChoice.addItem("Uşak")
        self.cityChoice.addItem("Van")
        self.cityChoice.addItem("Yozgat")
        self.cityChoice.addItem("Zonguldak")
        self.cityChoice.addItem("Aksaray")
        self.cityChoice.addItem("Bayburt")
        self.cityChoice.addItem("Karaman")
        self.cityChoice.addItem("Kırıkkale")
        self.cityChoice.addItem("Batman")
        self.cityChoice.addItem("Şırnak")
        self.cityChoice.addItem("Bartın")
        self.cityChoice.addItem("Ardahan")
        self.cityChoice.addItem("Iğdır")
        self.cityChoice.addItem("Yalova")
        self.cityChoice.addItem("Karabük")
        self.cityChoice.addItem("Kilis")
        self.cityChoice.addItem("Osmaniye")
        self.cityChoice.addItem("Düzce")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(20, 155, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 70, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 65, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.registerEmail = QtWidgets.QLineEdit(self.widget)
        self.registerEmail.setGeometry(QtCore.QRect(110, 15, 140, 24))
        self.registerEmail.setObjectName("registerEmail")
        self.registerPw = QtWidgets.QLineEdit(self.widget)
        self.registerPw.setGeometry(QtCore.QRect(110, 60, 140, 24))
        self.registerPw.setObjectName("registerPw")
        self.registerPwConfirm = QtWidgets.QLineEdit(self.widget)
        self.registerPwConfirm.setGeometry(QtCore.QRect(110, 105, 140, 24))
        self.registerPwConfirm.setObjectName("registerPwConfirm")
        self.registerName = QtWidgets.QLineEdit(self.widget)
        self.registerName.setGeometry(QtCore.QRect(110, 150, 140, 24))
        self.registerName.setObjectName("registerName")
        self.registerSurname = QtWidgets.QLineEdit(self.widget)
        self.registerSurname.setGeometry(QtCore.QRect(110, 195, 140, 24))
        self.registerSurname.setObjectName("registerSurname")
        self.registerButton = QtWidgets.QPushButton(self.widget)
        self.registerButton.setGeometry(QtCore.QRect(80, 290, 111, 41))
        self.registerButton.setObjectName("registerButton")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(30, 340, 211, 20))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.widget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(110, 20, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.loginEmail = QtWidgets.QLineEdit(self.widget_2)
        self.loginEmail.setGeometry(QtCore.QRect(35, 60, 200, 24))
        self.loginEmail.setObjectName("loginEmail")
        self.loginPw = QtWidgets.QLineEdit(self.widget_2)
        self.loginPw.setGeometry(QtCore.QRect(35, 160, 200, 24))
        self.loginPw.setText("")
        self.loginPw.setObjectName("loginPw")
        self.loginButton = QtWidgets.QPushButton(self.widget_2)
        self.loginButton.setGeometry(QtCore.QRect(80, 290, 111, 41))
        self.loginButton.setObjectName("loginButton")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(116, 120, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.rememberMeCBox = QtWidgets.QCheckBox(self.widget_2)
        self.rememberMeCBox.setGeometry(QtCore.QRect(170, 230, 81, 17))
        self.rememberMeCBox.setObjectName("rememberMeCBox")
        self.keepSignedInCBox = QtWidgets.QCheckBox(self.widget_2)
        self.keepSignedInCBox.setGeometry(QtCore.QRect(30, 230, 121, 17))
        self.keepSignedInCBox.setObjectName("keepSignedInCBox")
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.label_9.hide()

        # SETTING RESTRICTIONS AND SLOT-SIGNALS

        self.registerButton.clicked.connect(self.register)
        self.loginButton.clicked.connect(self.login)

        self.registerName.setMaxLength(100)
        self.registerSurname.setMaxLength(100)
        self.registerPw.setMaxLength(14)
        self.registerPwConfirm.setMaxLength(14)
        self.registerEmail.setMaxLength(320)

        self.loginEmail.setMaxLength(320)
        self.loginPw.setMaxLength(14)

        self.registerPw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.registerPwConfirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginPw.setEchoMode(QtWidgets.QLineEdit.Password)

        #####

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YemekSepeti"))
        self.label_5.setText(_translate("MainWindow", "Ad"))
        self.label_3.setText(_translate("MainWindow", "Soyad"))
        self.label_4.setText(_translate("MainWindow", "E-Posta"))
        self.label_2.setText(_translate("MainWindow", "Şifre Tekrar"))
        self.label.setText(_translate("MainWindow", "Şifre"))
        self.label_6.setText(_translate("MainWindow", "Şehir"))
        self.registerButton.setText(_translate("MainWindow", "Kayıt Ol"))
        self.label_7.setText(_translate("MainWindow", "E-Posta"))
        self.loginButton.setText(_translate("MainWindow", "Giriş Yap"))
        self.label_8.setText(_translate("MainWindow", "Şifre"))
        self.rememberMeCBox.setText(_translate("MainWindow", "Beni Hatırla"))
        self.keepSignedInCBox.setText(_translate("MainWindow", "Oturumumu açık tut"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Başarıyla Kayıt Oldunuz!</p></body></html>"))

    def register(self):
        register_form = {
            "email" : self.registerEmail.text(),
            "name" : self.registerName.text(),
            "surname" : self.registerSurname.text(),
            "password" : self.registerPw.text(),
            "password_confirmation" : self.registerPwConfirm.text(),
            "city" : str(self.cityChoice.currentText())
        }
        validation_context = util.validate_user_register(register_form)
        self.label_9.setText("<html><head/><body><p align=\"center\">"+validation_context['message']+"</p></body></html>")
        self.label_9.show()
        
        if validation_context['validated'] == True:
            try:
                util.save_customer(register_form)
            except OperationalError:
                util.create_tables()
                util.save_customer(register_form)
            except IntegrityError:
                self.label_9.setText("<html><head/><body><p align=\"center\">Bu E-Posta ile Zaten Kayıt Olunmuş!</p></body></html>")

    def login(self):
        login_form = {
            "email" : self.loginEmail.text(),
            "password" : self.loginPw.text(),
        }
        user_id = util.authenticate_user(login_form)
        print(user_id)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

