from PyQt5 import QtCore, QtGui, QtWidgets
import util

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(392, 575)
        MainWindow.setMinimumSize(QtCore.QSize(392, 575))
        MainWindow.setMaximumSize(QtCore.QSize(392, 575))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.cityChoice = QtWidgets.QComboBox(self.widget)
        self.cityChoice.setGeometry(QtCore.QRect(20, 70, 320, 20))
        self.cityChoice.setObjectName("cityChoice")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(20, 0, 81, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 50, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 250, 70, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.registerButton = QtWidgets.QPushButton(self.widget)
        self.registerButton.setGeometry(QtCore.QRect(20, 510, 111, 25))
        self.registerButton.setObjectName("registerButton")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(160, 510, 211, 20))
        self.label_9.setObjectName("label_9")
        self.townChoice = QtWidgets.QComboBox(self.widget)
        self.townChoice.setGeometry(QtCore.QRect(20, 120, 320, 20))
        self.townChoice.setObjectName("townChoice")
        self.districtChoice = QtWidgets.QComboBox(self.widget)
        self.districtChoice.setGeometry(QtCore.QRect(20, 170, 320, 20))
        self.districtChoice.setObjectName("districtChoice")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(20, 300, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(210, 300, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(20, 350, 161, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(210, 350, 121, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setGeometry(QtCore.QRect(20, 400, 51, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.restaurantNameInput = QtWidgets.QLineEdit(self.widget)
        self.restaurantNameInput.setGeometry(QtCore.QRect(20, 20, 320, 20))
        self.restaurantNameInput.setObjectName("restaurantNameInput")
        self.idNoInput = QtWidgets.QLineEdit(self.widget)
        self.idNoInput.setGeometry(QtCore.QRect(20, 220, 320, 20))
        self.idNoInput.setObjectName("idNoInput")
        self.addressInput = QtWidgets.QLineEdit(self.widget)
        self.addressInput.setGeometry(QtCore.QRect(20, 270, 320, 20))
        self.addressInput.setObjectName("addressInput")
        self.email_Input = QtWidgets.QLineEdit(self.widget)
        self.email_Input.setGeometry(QtCore.QRect(20, 420, 325, 20))
        self.email_Input.setObjectName("email_Input")
        self.restNumberInput = QtWidgets.QLineEdit(self.widget)
        self.restNumberInput.setGeometry(QtCore.QRect(210, 370, 130, 20))
        self.restNumberInput.setObjectName("restNumberInput")
        self.nameInput = QtWidgets.QLineEdit(self.widget)
        self.nameInput.setGeometry(QtCore.QRect(20, 320, 130, 20))
        self.nameInput.setObjectName("nameInput")
        self.ownerSurnameInput = QtWidgets.QLineEdit(self.widget)
        self.ownerSurnameInput.setGeometry(QtCore.QRect(210, 320, 130, 20))
        self.ownerSurnameInput.setObjectName("ownerSurnameInput")
        self.ownerNumberInput = QtWidgets.QLineEdit(self.widget)
        self.ownerNumberInput.setGeometry(QtCore.QRect(20, 370, 130, 20))
        self.ownerNumberInput.setObjectName("ownerNumberInput")
        self.passwordInput = QtWidgets.QLineEdit(self.widget)
        self.passwordInput.setGeometry(QtCore.QRect(20, 470, 130, 20))
        self.passwordConfirmation = QtWidgets.QLineEdit(self.widget)
        self.passwordConfirmation.setGeometry(QtCore.QRect(210, 470, 130, 20))
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(20, 450, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(210, 450, 72, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.cityChoice.addItem("Adana", ["Ceyhan", "Çukurova", "Konakoğlu Mah.", "Kozan", "Sarıçam", "Seyhan", "Yüreğir"])
        self.cityChoice.addItem("Adıyaman", ["Besni", "Çelikhan"])
        self.cityChoice.addItem("Afyon", ["Basmakçı", "Çay"])
        self.cityChoice.addItem("Ağrı", ["Diyadin", "Tutak"])
        self.cityChoice.addItem("Amasya", ["Hamamözü", "Merkez"])
        self.cityChoice.addItem("Ankara", ["Akyurt", "Etimesgut"])
        self.cityChoice.addItem("Antalya", ["Akseki", "Aksu"])
        self.cityChoice.addItem("Artvin", ["Ardanuç", "Hopa"])
        self.cityChoice.addItem("Aydın", ["Bozdoğan", "Çine"])
        self.cityChoice.addItem("Balıkesir", ["Ayvalık", "Balya"])
        self.cityChoice.addItem("Bilecik", ["Bozüyük", "Merkez"])
        self.cityChoice.addItem("Bingöl", ["Adaklı", "Genç"])
        self.cityChoice.addItem("Bitlis", ["Ahlat", "Hizan"])
        self.cityChoice.addItem("Bolu", ["Gerede", "Mudurnu"])
        self.cityChoice.addItem("Burdur", ["Bucak", "Gölhisar"])
        self.cityChoice.addItem("Bursa", ["Nilüfer", "Gürsu"])
        self.cityChoice.addItem("Çanakkale", ["Ayvacık", "Biga"])
        self.cityChoice.addItem("Çankırı", ["Orta", "Çerkeş"])
        self.cityChoice.addItem("Çorum", ["Alaca", "Bayat"])
        self.cityChoice.addItem("Denizli", ["Acıpayam", "Merkez"])
        self.cityChoice.addItem("Diyarbakır", ["Bağlar", "Çınar"])
        self.cityChoice.addItem("Edirne", ["Enez", "Keşan"])
        self.cityChoice.addItem("Elazığ", ["Ağın", "Baskil"])
        self.cityChoice.addItem("Erzincan", ["İliç", "Merkez"])
        self.cityChoice.addItem("Erzurum", ["Aşkale", "Çat"])
        self.cityChoice.addItem("Eskişehir", ["Tepebaşı", "Çifteler"])
        self.cityChoice.addItem("Gaziantep", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Giresun", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Gümüşhane", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Hakkari", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Hatay", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Isparta", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Mersin", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("İstanbul", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("İzmir", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Kars", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Kastamonu", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Kayseri", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Kırklareli", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Kırşehir", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Kocaeli", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Konya", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Kütahya", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Malatya", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Manisa", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Kahramanmaraş", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Mardin", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Muğla", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Muş", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Nevşehir", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Niğde", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Ordu", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Rize", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Sakarya", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Samsun", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Siirt", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Sinop", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Sivas", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Tekirdağ", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Tokat", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Trabzon", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Tunceli", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Şanlıurfa", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Uşak", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Van", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Yozgat", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Zonguldak", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Aksaray", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Bayburt", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Karaman", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Kırıkkale", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Batman", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Şırnak", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Bartın", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Ardahan", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Iğdır", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Yalova", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Karabük", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Kilis", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Osmaniye", ["İlçe 1", "İlçe 2"])
        self.cityChoice.addItem("Düzce", ["İlçe 1", "İlçe 2"])

        self.districtChoice.addItem("Semt A")
        self.districtChoice.addItem("Semt B")
        self.districtChoice.addItem("Semt C")
        self.districtChoice.addItem("Semt D")
        self.districtChoice.addItem("Semt F")
        self.districtChoice.addItem("Semt E")

        self.label_9.hide()

        #SETTING RESTRICTIONS AND SLOT-SIGNALS

        class BigIntValidator(QtGui.QDoubleValidator):

            def __init__(self, bottom=float('-inf'), top=float('inf')):
                super(BigIntValidator, self).__init__(bottom, top, 0)
                self.setNotation(QtGui.QDoubleValidator.StandardNotation)

            def validate(self, text, pos):
                if text.endswith('.'):
                    return QtGui.QValidator.Invalid, text, pos
                return super(BigIntValidator, self).validate(text, pos)

        self.restaurantNameInput.setMaxLength(200)
        self.idNoInput.setMaxLength(11)
        self.addressInput.setMaxLength(400)
        self.nameInput.setMaxLength(100)
        self.ownerSurnameInput.setMaxLength(100)
        self.restNumberInput.setMaxLength(11)
        self.ownerNumberInput.setMaxLength(11)
        self.email_Input.setMaxLength(320)
        self.passwordInput.setMaxLength(14)
        self.passwordConfirmation.setMaxLength(14)

        self.onlyInt = BigIntValidator()
        self.idNoInput.setValidator(self.onlyInt)
        self.restNumberInput.setValidator(self.onlyInt)
        self.ownerNumberInput.setValidator(self.onlyInt)

        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordConfirmation.setEchoMode(QtWidgets.QLineEdit.Password)

        self.registerButton.clicked.connect(self.register)
        
        ######

        self.cityChoice.currentIndexChanged.connect(self.cityChoiceIndexChanged)
        self.cityChoiceIndexChanged(self.cityChoice.currentIndex())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YemekSepeti"))
        self.label_5.setText(_translate("MainWindow", "Semt"))
        self.label_3.setText(_translate("MainWindow", "TCKN"))
        self.label_4.setText(_translate("MainWindow", "Restoran Adı"))
        self.label_2.setText(_translate("MainWindow", "İlçe"))
        self.label.setText(_translate("MainWindow", "Şehir"))
        self.label_6.setText(_translate("MainWindow", "Adres"))
        self.registerButton.setText(_translate("MainWindow", "Kayıt Ol"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Başarıyla Kayıt Oldunuz!</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Ad"))
        self.label_11.setText(_translate("MainWindow", "Soyad"))
        self.label_12.setText(_translate("MainWindow", "Restoran Sahibi Telefon No."))
        self.label_13.setText(_translate("MainWindow", "Restoran Telefon No."))
        self.label_14.setText(_translate("MainWindow", "E-Posta"))
        self.label_7.setText(_translate("MainWindow", "Şifre"))
        self.label_8.setText(_translate("MainWindow", "Şifre Tekrar"))

    def cityChoiceIndexChanged(self, index):
        self.townChoice.clear()
        data = self.cityChoice.itemData(index)
        if data is not None:
            self.townChoice.addItems(data)

    def register(self):
        register_form = {
            "email": self.email_Input.text(),
            "name": self.restaurantNameInput.text(),
            "owner_name": self.nameInput.text(),
            "owner_surname": self.ownerSurnameInput.text(),
            "password": self.passwordInput.text(),
            "password_confirmation": self.passwordConfirmation.text(),
            "city": str(self.cityChoice.currentText()),
            "town": str(self.townChoice.currentText()),
            "district": str(self.districtChoice.currentText()),
            "address": self.addressInput.text(),
            "owner_ssn" : self.idNoInput.text(),
            "phone_number" : self.restNumberInput.text(),
            "owner_phone_number": self.ownerNumberInput.text(),
        }
        validation_context = util.validate_owner_register(register_form)
        self.label_9.setText("<html><head/><body><p align=\"center\">"+validation_context['message']+"</p></body></html>")
        self.label_9.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

